Initial project setup
michal-lepik/instapound pull request #1
Opened 2019-07-04 09:38 UTC by michal-lepik

2019-07-04 09:58 UTC, grzegorz-bielski commented on frontend/dev.Dockerfile
> +COPY . .
First copy package.json+lock, then install all deps, then copy rest of the code. Thanks to that all deps will be cached in the previous temp container layer and you get faster builds.

2019-07-04 09:59 UTC, grzegorz-bielski commented on nginx/Dockerfile
> +COPY nginx.conf /etc/nginx/conf.d/nginx.conf
Use multi-stage builds for the minimal final image.

2019-07-04 10:00 UTC, grzegorz-bielski commented on docker-compose.yml
> +networks:
is that necessary? You can remove it and live within a default network

2019-07-04 10:03 UTC, grzegorz-bielski commented on Makefile
> +	docker-compose build
- Use `--parallel` for faster builds. 
- Add a command for installing node-deps locally. 
```
install-local-dependencies:
	npm --prefix ./frontend/ install
```

2019-07-04 10:04 UTC, grzegorz-bielski commented on Makefile
> +	docker-compose up
add ` --remove-orphans`

2019-07-04 10:05 UTC, grzegorz-bielski commented on Makefile
> +	docker-compose up
Also, where is `docker-compose` for prod/staging? Please create it in this PR.

2019-07-04 10:08 UTC, grzegorz-bielski commented on docker-compose.yml
> +      - ./frontend:/frontend
Use `:delegated` for better performance in the dev volumes: `./frontend:/frontend:delegated`

2019-07-04 10:09 UTC, grzegorz-bielski commented on docker-compose.yml
> +      - 4200:80
You might consider moving this to the `$HOSTPORT` env ... or not (I'd do that).

2019-07-04 10:10 UTC, grzegorz-bielski commented on docker-compose.yml
> +    restart: always
This can be annoying, you might want to use `unless-stopped`

2019-07-04 10:14 UTC, grzegorz-bielski commented
In addition, create `.dockerignore` that have at least this stuff (for JS Project):
```
node_modules
npm-debug.log
Dockerfile*
.dockerignore
.git
README
LICENSE
```
Thank to that the docker won't load `node_modules` when creating images (during `COPY`), so the builds will be faster.

2019-07-04 10:14 UTC, grzegorz-bielski requested changes
/\ comments

2019-07-05 08:45 UTC, mateuszkozakiewicz commented on .dockerignore
> +Dockerfile*
Your files are named for example dev.Dockerfile so here should be *Dockerfile

2019-07-05 08:47 UTC, mateuszkozakiewicz approved these changes

2019-07-05 09:10 UTC, merged