Create basic homepage
michal-lepik/instapound pull request #2
Opened 2019-07-09 13:21 UTC by michal-lepik

2019-07-09 13:25 UTC, arkadiusz-sapek requested changes

2019-07-09 13:25 UTC, ArkadiuszSa commented on frontend/src/app/services/comments.service.ts
> +@Injectable({
It better to import in module

2019-07-10 07:30 UTC, achromik approved these changes

2019-07-10 07:45 UTC, PiotrAdamus commented on frontend/src/app/app.component.html
> +<div>
Are you sure u need this div ? U can style your component with `:host` pseudoselector

2019-07-10 07:45 UTC, PiotrAdamus commented on frontend/src/app/components/icon-button/icon-button.component.scss
> +img {
Dont style by tag pls :D

2019-07-17 06:29 UTC, merged